# Generated by Django 4.0.1 on 2022-02-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camda',
            new_name='camada',
        ),
    ]
